# Generated by Django 5.1.5 on 2025-01-24 03:01

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_votes', models.IntegerField()),
                ('stroke', models.IntegerField()),
                ('let', models.IntegerField()),
                ('no_let', models.IntegerField()),
                ('stroke_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('let_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('no_let_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('video_title', models.CharField(max_length=500)),
                ('timestamp', models.CharField(max_length=50)),
                ('video_id', models.CharField(max_length=255)),
                ('comment_id', models.CharField(max_length=255)),
                ('org_decision', models.CharField(choices=[('Stroke', 'Stroke'), ('Let', 'Let'), ('No Let', 'No Let')], max_length=20)),
            ],
        ),
    ]
