# Generated by Django 5.1.5 on 2025-03-09 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vote", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="YoutubeQuota",
        ),
    ]
