# Generated by Django 5.1.8 on 2025-06-20 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vote", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
