# Generated by Django 5.1.8 on 2025-06-22 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vote", "0002_video_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="needs_review",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="video",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
