# Generated by Django 5.1.5 on 2025-01-24 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_result_delete_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='video',
            name='is_posted',
            field=models.BooleanField(default=False),
        ),
    ]
