# Generated by Django 5.1.5 on 2025-03-10 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vote", "0002_delete_youtubequota"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="video_id",
            field=models.CharField(max_length=512, unique=True),
        ),
        migrations.AlterField(
            model_name="voteuser",
            name="vote",
            field=models.CharField(
                choices=[("let", "Let"), ("stroke", "Stroke"), ("nolet", "No Let")],
                max_length=20,
            ),
        ),
    ]
