# Generated by Django 5.1.5 on 2025-03-18 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vote", "0003_alter_video_video_id_alter_voteuser_vote"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="comment_id",
        ),
        migrations.RemoveField(
            model_name="video",
            name="is_posted",
        ),
    ]
