# Generated by Django 5.1.8 on 2025-06-22 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vote", "0003_video_needs_review_alter_video_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
