# Generated by Django 5.1.8 on 2025-06-30 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vote", "0004_alter_video_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[("PSA", "Psa"), ("Amateur", "Amateur")],
                max_length=10,
                null=True,
            ),
        ),
    ]
