# Generated by Django 5.1.5 on 2025-01-29 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vote", "0005_video_slug_alter_result_total_votes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="slug",
        ),
    ]
