# Generated by Django 5.1.5 on 2025-02-02 22:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vote", "0006_remove_video_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Last_Update",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_update", models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
