# Generated by Django 5.1.5 on 2025-02-06 05:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vote", "0007_last_update"),
    ]

    operations = [
        migrations.CreateModel(
            name="YoutubeQuota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(default=django.utils.timezone.now, unique=True),
                ),
                ("quota", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name="Last_Update",
        ),
    ]
