# Generated by Django 5.1.5 on 2025-02-06 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vote", "0008_youtubequota_delete_last_update"),
    ]

    operations = [
        migrations.CreateModel(
            name="VoteUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("youtube_user_id", models.CharField(max_length=255)),
                (
                    "vote",
                    models.CharField(
                        choices=[
                            ("Stroke", "Stroke"),
                            ("Let", "Let"),
                            ("No Let", "No Let"),
                        ],
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="vote.video"
                    ),
                ),
            ],
            options={
                "unique_together": {("video", "youtube_user_id")},
            },
        ),
    ]
